language: r

addons:
  apt:
    packages:
      - python2.7
      - python-pip
      
before_install:
- cp clustering/* .
- cp sentiment_analysis/* .
- cp supervised_learning/* .
- cp unsupervised_learning/* .
- pip install requests beautifulsoup4

install:
- for package in xgboost tm readr wordcloud rvest RCurl openNLP NLP qdap SnowballC; do R -e "install.packages('$package')"; done 

script:
- Rscript wikipedia_parser.R
- Rscript wikipedia_analyzer.R
- Rscript sentiment_analysis.R
- Rscript supervised_learning.R
- python napimigrans_parser.py