language: r

before_install:
- cp clustering/* .
- cp sentiment_analysis/* .
- cp supervised_learning/* .

install:
- for package in xgboost tm readr wordcloud rvest RCurl openNLP NLP qdap; do R -e "install.packages('$package')"; done 

script:
- Rscript wikipedia_parser.R
- Rscript wikipedia_analyzer.R
- Rscript sentiment_analysis.R
- Rscript supervised_learning.R