language: r

sudo: required

addons:
  apt:
    packages:
      - python2.7
      - python-pip
      - python-matplotlib
      - python-pandas
      
before_install:
- cp clustering/* .
- cp sentiment_analysis/* .
- cp supervised_learning/* .
- cp unsupervised_learning/* .
- sudo pip install -r requirements.txt

install:
- for package in xgboost tm readr wordcloud rvest RCurl openNLP NLP qdap SnowballC; do R -e "install.packages('$package')"; done 

script:
- Rscript wikipedia_parser.R
- Rscript wikipedia_analyzer.R
- Rscript sentiment_analysis.R
- Rscript supervised_learning.R
- python napimigrans_parser.py
- sudo runipy napimigrans_analysis.ipynb